apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cd-project
  template:
    metadata:
      labels:
        app: ci-cd-project
    spec:
      containers:
        - name: ci-cd-project
          image: phyothetkhaing/sample-api:1697988a2b5533f317d68ac3472a2e8e8f609682
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-project
spec:
  selector:
    app: ci-cd-project
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
